{% set name = "pnpm-licenses" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://registry.npmjs.org/@quantco/pnpm-licenses/-/pnpm-licenses-{{ version }}.tgz
  sha256: 33d0fb35181479f4439cb41a719f34a5a7371f9af1aa11440b64e96ee9388d28

build:
  number: 1

requirements:
  build:
    - nodejs
  host:
    - nodejs
    - pnpm >=8.6.12
  run:
    - nodejs

test:
  commands:
    - pnpm-licenses --version
    - test -d $PREFIX/lib/node_modules/@quantco/pnpm-licenses  # [unix]
    - if not exist %LIBRARY_INC%\share\pnpm-licenses\node_modules\.bin\pnpm-licenses.cmd exit 1  # [win]

about:
  home: https://github.com/Quantco/pnpm-licenses
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Generate third party license disclaimers in pnpm-based projects

extra:
  recipe-maintainers:
    - JannikWibkerQC
    - pavelzw
    - xhochy
