{% set name = "pnpm-licenses" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://registry.npmjs.org/@quantco/pnpm-licenses/-/pnpm-licenses-{{ version }}.tgz
  sha256: e5742d991d7436db96fd09c647fdf693999c27495639319a86ca146c0e0009af

build:
  # https://github.com/conda-forge/pnpm-feedstock/issues/31
  skip: true  # [win]
  number: 1

requirements:
  build:
    - nodejs
  host:
    - nodejs
    - pnpm
  run:
    - nodejs

test:
  commands:
    - test -d $PREFIX/lib/node_modules/@quantco/pnpm-licenses  # [unix]
    - if not exist %LIBRARY_INC%\lib\node_modules\@quantco\pnpm-licenses exit 1  # [win]
    - pnpm-licenses --version

about:
  home: https://github.com/Quantco/pnpm-licenses
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Generate third party license disclaimers in pnpm-based projects

extra:
  recipe-maintainers:
    - JannikWibkerQC
    - pavelzw
