schema_version: 1

context:
  version: "2.4.0"

package:
  name: pnpm-licenses
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@quantco/pnpm-licenses/-/pnpm-licenses-${{ version }}.tgz
  sha256: 1168a44b2aa0080833b564340c90ff7c405f313c740a10d25443c422a77a7dde

build:
  number: 0

requirements:
  build:
    - nodejs
  host:
    - nodejs
    - pnpm >=8.6.12
  run:
    - nodejs

tests:
  - script:
      - pnpm-licenses --version
  - package_contents:
      strict: true
      bin:
        - pnpm-licenses
      files:
        - if: unix
          then:
            - lib/node_modules/@quantco/pnpm-licenses/**/*
          else:
            - Library/share/pnpm-licenses/**/*
            - Library/share/pnpm-licenses/node_modules/.bin/pnpm-licenses.cmd

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Generate third party license disclaimers in pnpm-based projects
  homepage: https://github.com/Quantco/pnpm-licenses

extra:
  recipe-maintainers:
    - JaninaWibkerQC
    - pavelzw
    - xhochy
