schema_version: 1

context:
  name: pnpm-licenses
  version: "2.2.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@quantco/pnpm-licenses/-/pnpm-licenses-${{ version }}.tgz
  sha256: 7df2d6aed0526907f11200450728133211a0221503476b734f80dc1fb09f3486

build:
  number: 1

requirements:
  build:
    - nodejs
  host:
    - nodejs
    - pnpm >=8.6.12
  run:
    - nodejs

tests:
  - script:
      - pnpm-licenses --version
  - package_contents:
      files:
        - if: unix
          then:
            - lib/node_modules/@quantco/pnpm-licenses
          else:
            - share/pnpm-licenses/node_modules/.bin/pnpm-licenses.cmd

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Generate third party license disclaimers in pnpm-based projects
  homepage: https://github.com/Quantco/pnpm-licenses

extra:
  recipe-maintainers:
    - JaninaWibkerQC
    - pavelzw
    - xhochy
